### PR TITLE
Deploy Application on Github pages 

### PR DESCRIPTION
**Pull request by Talha-Hanif5666**
In this PR, the portfolio webpage is deployed on the Github pages. The "Readme.md" file is updated and the live version link of the webpage is present in the readme.md file.

### CODE REVIEW

**Review by ha-manel — APPROVED** [review]
# STATUS: APPROVED ✅
## Hi @Talha-Hanif5666 👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**



## Highlights:
* Well written PR description ✔️ 
* All tests passed ✔️
* The website is deployed correctly ✔️  


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tsohleDev** [comment]
Great Work 😄 

- Correct GitHub flow 👍 
- No linters Errors 😃 
- Live Website 😉

**Comment by Habtamu210** [comment]
Appreciations:
- It is based on the figma design
- you have used the most readable styling 
- class names are descriptive

**Comment by lawrahkonwea** [comment]
Great work:
- The Figma design was followed properly.

**Pull request merged**
